### ISSUE TITLE
Баг вкладки "выжившие". 

### ISSUE THREAD

**Issue by chigriil** [dimon58/NeedForOtl10#1]
При нажатии кнопки "Выжившие" появляется белый прямоугольник, но при этом хоть отрисовки кнопок и нет, если тыкать на их прошлые места положения все равно можно начать игру или выйти вообще. 

- [x] Исправить данный баг, чтобы не было кнопок в окне выжившие из окна главного меню. 

- [x] Сделать выход (кнопку выход) из окна выжившие в главное меню

**Comment by EugeneMorar** [comment]
Добавил отдельный класс для окна "Выжившие". Убрал кнопки главного меню. Добавил кнопку выход из этого окна в главное меню.
