### ISSUE TITLE
Баг черного экрана при нажатии "начать"

### ISSUE THREAD

**Issue by chigriil** [dimon58/NeedForOtl10#2]
При нажатии кнопки "начать" появляется черный экран с непонятной по необходимости прямоугольной рамкой серого цвета. Чтобы приступить к игре необходимо нажать ЛКЛ. Какое предназначение данного таинственного экрана, если его нет, то убрать его вообще. 

- [x] Объяснить предназначение черного экрана, который появляется при нажатии кнопки "начать"

- [x] При отсутствии действительно необходимого предназначения из первого пункта убрать данный баг.

**Comment by EugeneMorar** [comment]
Черный экран был заготовкой окна кастомизации персонажа. Теперь это видно.
