### ISSUE TITLE
Движение игрока

### ISSUE THREAD

**Issue by EugeneMorar** [dimon58/NeedForOtl10#3]
При первом нажатии клавиши движения он продолжает движение и при её отжатии.

**Comment by EugeneMorar** [comment]
При запрыгивании на блок, блок начинает двигаться вместе с игроком.

**Comment by dimon58** [comment]
Это к Юре. Он трение не добавил при загрузке сохранений

**Comment by dimon58** [comment]
Пофикшено добавлением трения для сегментов
