### ISSUE TITLE
Кривое меню

### ISSUE THREAD

**Issue by dimon58** [dimon58/NeedForOtl10#5]
Сделай меню маштабируемым. Его геометрия должна быть привязана к отношению сторон, а не к конкретным значениям.
![Безымянный](https://user-images.githubusercontent.com/67104904/101543090-cfe94580-39b4-11eb-9cfd-2b46164141cc.png)

**Comment by EugeneMorar** [comment]
Только шрифт был привязан к значениям. Уже исправлен.
